"""Claude Code hook generation and installation."""

import stat
from pathlib import Path

HOOKS_DIR = Path.home() / ".ccmux" / "hooks" / "claude-code"

SESSION_START_SCRIPT = """\
#!/bin/bash
# ccmux hook: Register session on Claude Code start
# Auto-generated by: ccmux install-hooks

INPUT=$(cat)
SESSION_ID=$(echo "$INPUT" | jq -r '.session_id // empty')
[ -z "$SESSION_ID" ] && exit 0

# Get Ghostty terminal UUID (fast no-op if not in Ghostty)
GHOSTTY_UUID=""
if [ "${TERM_PROGRAM:-}" = "ghostty" ]; then
    GHOSTTY_UUID=$(osascript -e 'tell application "Ghostty" to get id of focused terminal of selected tab of front window' 2>/dev/null || true)
fi

if [ -n "$GHOSTTY_UUID" ]; then
    ccmux agent-event start --claude-session-id "$SESSION_ID" --ghostty-uuid "$GHOSTTY_UUID" 2>/dev/null
else
    ccmux agent-event start --claude-session-id "$SESSION_ID" 2>/dev/null
fi

exit 0
"""

SESSION_END_SCRIPT = """\
#!/bin/bash
# ccmux hook: Mark session as detached on Claude Code end
# Auto-generated by: ccmux install-hooks

INPUT=$(cat)
SESSION_ID=$(echo "$INPUT" | jq -r '.session_id // empty')
[ -z "$SESSION_ID" ] && exit 0

ccmux agent-event stop --claude-session-id "$SESSION_ID" 2>/dev/null

exit 0
"""


def generate_hook_script(event: str) -> str:
    if event == "SessionStart":
        return SESSION_START_SCRIPT
    elif event in ("SessionStop", "SessionEnd"):
        return SESSION_END_SCRIPT
    else:
        raise ValueError(f"Unknown hook event: {event}")


def get_hooks_config() -> dict:
    return {
        "hooks": {
            "SessionStart": [
                {
                    "matcher": "",
                    "hooks": [
                        {
                            "type": "command",
                            "command": str(HOOKS_DIR / "on-session-start.sh"),
                            "timeout": 5,
                        }
                    ],
                }
            ],
            "SessionEnd": [
                {
                    "matcher": "",
                    "hooks": [
                        {
                            "type": "command",
                            "command": str(HOOKS_DIR / "on-session-end.sh"),
                            "timeout": 5,
                        }
                    ],
                }
            ],
        }
    }


def install_hooks() -> list[Path]:
    HOOKS_DIR.mkdir(parents=True, exist_ok=True)
    created = []
    scripts = {
        "on-session-start.sh": SESSION_START_SCRIPT,
        "on-session-end.sh": SESSION_END_SCRIPT,
    }
    for filename, content in scripts.items():
        path = HOOKS_DIR / filename
        path.write_text(content)
        path.chmod(path.stat().st_mode | stat.S_IEXEC)
        created.append(path)
    return created
