"""Claude Code hook generation and installation."""

import json
import stat
from pathlib import Path

HOOKS_DIR = Path.home() / ".ccmux" / "hooks" / "claude-code"

SESSION_START_SCRIPT = """\
#!/bin/bash
# ccmux hook: Register session on Claude Code start
# Auto-generated by: ccmux install-hooks

INPUT=$(cat)
SESSION_ID=$(echo "$INPUT" | jq -r '.session_id // empty')
[ -z "$SESSION_ID" ] && exit 0

# Get Ghostty terminal UUID (fast no-op if not in Ghostty)
GHOSTTY_UUID=""
if [ "${TERM_PROGRAM:-}" = "ghostty" ]; then
    GHOSTTY_UUID=$(osascript -e 'tell application "Ghostty" to get id of focused terminal of selected tab of front window' 2>/dev/null || true)
fi

if [ -n "$GHOSTTY_UUID" ]; then
    ccmux agent-event start --claude-session-id "$SESSION_ID" --ghostty-uuid "$GHOSTTY_UUID" 2>/dev/null
else
    ccmux agent-event start --claude-session-id "$SESSION_ID" 2>/dev/null
fi

exit 0
"""

SESSION_END_SCRIPT = """\
#!/bin/bash
# ccmux hook: Mark session as detached on Claude Code end
# Auto-generated by: ccmux install-hooks

INPUT=$(cat)
SESSION_ID=$(echo "$INPUT" | jq -r '.session_id // empty')
[ -z "$SESSION_ID" ] && exit 0

ccmux agent-event stop --claude-session-id "$SESSION_ID" 2>/dev/null

exit 0
"""


def generate_hook_script(event: str) -> str:
    if event == "SessionStart":
        return SESSION_START_SCRIPT
    elif event in ("SessionStop", "SessionEnd"):
        return SESSION_END_SCRIPT
    else:
        raise ValueError(f"Unknown hook event: {event}")


def get_hooks_config() -> dict:
    return {
        "hooks": {
            "SessionStart": [
                {
                    "matcher": "",
                    "hooks": [
                        {
                            "type": "command",
                            "command": str(HOOKS_DIR / "on-session-start.sh"),
                            "timeout": 5,
                        }
                    ],
                }
            ],
            "SessionEnd": [
                {
                    "matcher": "",
                    "hooks": [
                        {
                            "type": "command",
                            "command": str(HOOKS_DIR / "on-session-end.sh"),
                            "timeout": 5,
                        }
                    ],
                }
            ],
        }
    }


def install_hooks() -> list[Path]:
    """Write hook scripts to disk."""
    HOOKS_DIR.mkdir(parents=True, exist_ok=True)
    created = []
    scripts = {
        "on-session-start.sh": SESSION_START_SCRIPT,
        "on-session-end.sh": SESSION_END_SCRIPT,
    }
    for filename, content in scripts.items():
        path = HOOKS_DIR / filename
        path.write_text(content)
        path.chmod(path.stat().st_mode | stat.S_IEXEC)
        created.append(path)
    return created


CLAUDE_SETTINGS = Path.home() / ".claude" / "settings.json"


def merge_hooks_into_settings() -> bool:
    """Merge ccmux hook entries into ~/.claude/settings.json.

    Overwrites any existing ccmux hooks (matched by command path containing
    '.ccmux/hooks/'), preserves non-ccmux hooks. Returns True if modified.
    """
    if not CLAUDE_SETTINGS.exists():
        return False

    with open(CLAUDE_SETTINGS) as f:
        settings = json.load(f)

    hooks = settings.setdefault("hooks", {})
    ccmux_hooks = get_hooks_config()["hooks"]
    modified = False

    for event, new_entries in ccmux_hooks.items():
        existing = hooks.get(event, [])
        # Remove any existing ccmux hooks
        filtered = [
            h for h in existing
            if not any(".ccmux/hooks/" in hh.get("command", "") for hh in h.get("hooks", []))
        ]
        hooks[event] = filtered + new_entries
        if hooks[event] != existing:
            modified = True

    if modified:
        with open(CLAUDE_SETTINGS, "w") as f:
            json.dump(settings, f, indent=2)
            f.write("\n")

    return modified
